name: client
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0-279.0.dev

# Add regular dependencies here.
dependencies:
  http: ^1.2.0
  vector_math: ^2.1.4
  web: ^0.4.0
  web_socket_channel: ^2.4.3

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^3.0.0
